---
- name: Descargar repositorio
  hosts: all
  tasks:

    - name: Git add .
      command: chdir=/home/repo/ git add .
    
    - name: git commit 
      command: chdir=/home/repo/ git commit -m "{{Mensaje commit}}"

    - name: git push origin
      ansible.builtin.expect:
        command: chdir=/home/repo/ git push origin main
        responses:
          Username: "aroyoredhat"
          Password: "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"