---
- name: Descargar repositorio
  hosts: all

  tasks:
    - name: 10005 - SETUP | https loca repo ahead.
      register: result
      git_acp:
        user: "{{ user }}"
        token: "{{ token }}"
        path: "{{ working_dir }}"
        branch: master
        add: ["."]
        comment: Local repo ahead
        mode: https
        url: "https://gitlab.com/networkAutomation/git_test_module.git"
    - name: HTTPS | push all changes.
      git_acp:
        user: aroyoredhat
        token: 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
        path: /home/repo/
        branch: master
        comment: Add all the thinghs.
        add: [ "." ]
        mode: https
        url: "https://github.com/aroyoredhat/playbooks-ubiipagos.git"
    