---
- name: Instalar java
  hosts: web

  tasks:
    - name: Update APT package manager repositories cache
      become: true
      yum:
        update_cache: yes
    - name: Install Java using Ansible
      become: yes
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
