---
- name: Instalar java
  hosts: all

  tasks:
    - name: Update repos
      yum:
        name: "*"
        state: latest
    - name: Install Java using Ansible
      yum:
        name: java-1.8.0-openjdk