---
- name: playbook completo
  hosts: node1
  tasks:
    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /tmp/archivoPrueba.jar
        dest: /tmp/
      delegate_to: ansible-1