---
- name: playbook completo
  hosts: node1

  tasks:
  - name: Case insensitive password string match
    ansible.builtin.expect:
      command: scp -p student1@ansible-1:/tmp/archivoPrueba.jarXX.jar /tmp/
      responses:
        (?i)password: "iFfg3mf1mF03Pf"