---
- name: playbook completo
  hosts: all
  tasks:
    - name: SCP
      shell: scp -p node1.example.com:/home/repo/rhel/Ubiipagos/executablejarexample/{{nuevoJar}}.jar /home/ec2-user/Prueba
      delegate_to: node2.example.com

    - name: Bajar el servicio
      command: pkill -9 -f {{nombreJar}}.jar
    
    - name: Cambiar nombre antiguo jar
      command: mv /home/repo/rhel/Ubiipagos/executablejarexample/{{nombreJar}}.jar /home/repo/rhel/Ubiipagos/executablejarexample/{{antiguoJar}}.jar
    
    - name: Mover el nuevo jar a la carpetaJar
      command: mv /home/ec2-user/Prueba/{{nuevoJar}}.jar /home/carpetaJar/

    - name: Levantar el nuevo proceso
      command: nohup java -jar /home/carpetaJar/{{nuevoJar}}.jar &> BankService_04052022_3.out 2>&1&
      delegate_to: node2.example.com
    
