---
- name: playbook completo
  hosts: node1
  tasks:
    - name: Transfer file from ServerA to ServerB
      copy:
        src: /tmp/archivoPrueba.jar
        dest: /tmp/archivoPrueba.jar
      delegate_to: ansible-1