---
- name: playbook completo
  hosts: node1
  tasks:
    - name: Transfer file from ServerA to ServerB
      copy:
        src: /home/student1/deployment/archivoPrueba.jar
        dest: /home/ec2-user/deployment/
        remote_src: yes
      delegate_to: ansible-1