---
- name: playbook completo
  hosts: server1

  tasks:
  - name: Ir a la carpeta
    chdir: home/Repo 
    
  - name: Realizar conexion jar
    copy:
      src=/home/Repo
      dest=home/
    delegate_to: server2