---
- name: playbook completo
  hosts: all
  tasks:
    - name: SCP
      shell: scp -p {{nodoAcceso}}:{{rutaNuevoJar}} {{rutaGuardarJar}}
      delegate_to: "{{nodoProd}}"

    - name: Bajar el servicio
      command: pkill -9 -f {{nombreJar}}.jar
    
    - name: Cambiar nombre antiguo jar
      command: mv {{nombreJar}} {{antiguoJar}}
    
    - name: Mover el nuevo jar a la carpetaJar
      command: mv {{rutaGuardarJar}} {{carpetaJar}}

    - name: Levantar el nuevo proceso
      shell: nohup java -jar {{rutaProceso}} &> {{rutaOut}} 2>&1&
      delegate_to: "{{nodoProd}}"
    
