---
- name: Descargar repositorio
  hosts: all

  tasks:
  - name: Install git
    ansible.builtin.dnf:
      name: git
      state: present
      update_cache: yes

  - name: Clonar repositorio
    ansible.builtin.git:
       repo: https://github.com/aroyoredhat/playbooks-ubiipagos.git
       dest: /home/

  - name: SCP
    copy:
      src: /home/ec2-user/deployment/archivoPrueba.jar
      dest: /home/
      remote_src: yes
    delegate_to: node1