---
- name: Descargar repositorio
  hosts: all

  tasks:
  - name: Install git
    yum:
      name: git
      state: present
      update_cache: yes

  

  - name: SCP
    shell: scp -p ec2-user@node1.example.com:/home/ec2-user/deployment/archivoPrueba.jar /home/ec2-user/Prueba
    delegate_to: node2.example.com


