---
- name: Descargar repositorio
  hosts: server1

  tasks:
  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes
      
  - name: Clonar repositorio
    ansible.builtin.git:
       repo: https://github.com/aroyoredhat/playbooks-ubiipagos.git
       dest: /home/Repo
